<?php

use App\Models\Asset;
use App\Models\AssetDepreciationEntry;
use App\Models\AssetDisposal;
use App\Models\AssetMaintenance;
use App\Models\AssetMedia;
use App\Models\MediaAsset;
use App\Models\Organization;
use App\Models\OrganizationGroup;
use App\Models\TechnicianProfile;
use App\Models\User;
use Database\Seeders\DatabaseSeeder;
use Database\Seeders\DemoAssetDataSeeder;
use Database\Seeders\DemoMasterDataSeeder;
use Database\Seeders\DemoOperationsSeeder;
use Illuminate\Support\Facades\Http;

test('demo asset seeder creates organizations, assets, and photos', function () {
    $png = base64_decode(
        // 1x1 PNG generated by GD (valid for imagecreatefromstring()).
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAADElEQVQImWP4z8AAAAMBAQCc479ZAAAAAElFTkSuQmCC',
        true,
    );
    expect($png)->not->toBeFalse();

    Http::fake([
        'https://commons.wikimedia.org/wiki/Special:FilePath/*' => Http::response($png, 200, ['Content-Type' => 'image/png']),
    ]);

    $this->seed(DatabaseSeeder::class);
    $this->seed(DemoMasterDataSeeder::class);
    $this->seed(DemoAssetDataSeeder::class);
    $this->seed(DemoOperationsSeeder::class);

    $group = OrganizationGroup::query()->where('slug', 'pt-maju-bersama')->first();
    expect($group)->not->toBeNull();

    expect(Organization::query()->where('organization_group_id', $group->id)->count())->toBe(3);
    expect(Organization::query()->count())->toBeGreaterThanOrEqual(3);

    expect(Asset::withoutGlobalScopes()->count())->toBeGreaterThan(0);
    expect(MediaAsset::query()->count())->toBeGreaterThan(0);

    expect(AssetMedia::withoutGlobalScopes()->where('kind', 'photo')->count())->toBeGreaterThan(0);
    expect(AssetMedia::withoutGlobalScopes()->where('kind', 'document')->count())->toBeGreaterThan(0);

    expect(TechnicianProfile::withoutGlobalScopes()->count())->toBeGreaterThan(0);
    expect(AssetMaintenance::withoutGlobalScopes()->count())->toBeGreaterThan(0);

    $overdue = AssetMaintenance::withoutGlobalScopes()
        ->whereNotNull('response_due_at')
        ->whereNull('acknowledged_at')
        ->where('status', 'open')
        ->where('response_due_at', '<', now())
        ->count();
    expect($overdue)->toBeGreaterThanOrEqual(1);

    expect(AssetDepreciationEntry::withoutGlobalScopes()->count())->toBeGreaterThan(0);

    expect(AssetDisposal::withoutGlobalScopes()->count())->toBeGreaterThan(0);
    expect(AssetDisposal::withoutGlobalScopes()->where('status', 'pending')->count())->toBeGreaterThanOrEqual(1);
    expect(AssetDisposal::withoutGlobalScopes()->where('status', 'executed')->count())->toBeGreaterThanOrEqual(1);
    expect(Asset::withoutGlobalScopes()->whereNotNull('archived_at')->count())->toBeGreaterThanOrEqual(1);

    $platformSuperAdmin = User::query()->where('email', 'superadmin@example.com')->first();
    $platformAdmin = User::query()->where('email', 'admin@example.com')->first();

    expect($platformSuperAdmin)->not->toBeNull();
    expect($platformAdmin)->not->toBeNull();

    $demoOrganizations = Organization::query()
        ->where('organization_group_id', $group->id)
        ->get(['id', 'slug']);

    expect($demoOrganizations)->toHaveCount(3);

    foreach ($demoOrganizations as $organization) {
        expect($platformSuperAdmin->organizations()
            ->whereKey($organization->id)
            ->wherePivot('role', 'Owner')
            ->wherePivot('is_active', true)
            ->exists())->toBeTrue();

        expect($platformAdmin->organizations()
            ->whereKey($organization->id)
            ->wherePivot('role', 'Admin')
            ->wherePivot('is_active', true)
            ->exists())->toBeTrue();
    }
});
